### ISSUE TITLE
Job name must be formatted.

### ISSUE THREAD

**Issue by gduggirala** [googleapis/nodejs-scheduler#114]
#### Environment details

  - OS: Mac
  - Node.js version: v12.4.0
  - npm version: 6.9.0
  - `@google-cloud/scheduler` version: I am using 
googleapis: ^41.0.0

#### Steps to reproduce

  1. Create a typescript file which is using Google scheduler API and execute we get this error.
```
var request = {
      parent: `projects/${ScheduleJobService.client.projectId}/locations/us-central1`,
      resource: {
        name: "nameJob",
        description: "This is description",
        schedule: "* * * * *",
        httpTarget: {
          "uri": "https://sign.ly",
          "httpMethod": "GET"
        }
      },
      auth: ScheduleJobService.client,
    };

 cloudScheduler.projects.locations.jobs.create(request,
      {url: 'https://cloudscheduler.googleapis.com/v1/projects/<Took it off purposefully>/locations/us-central1/jobs'},
      function (err: any, response: any) {
        if (err) {
          console.error('Exception while creating a job.', err);
          return;
        }else{
          console.log(JSON.stringify(response, null, 2));
        }
      });

```
I tried with out the 'url' option in create(), but I am getting the same error.

```
Exception while creating a job. GaxiosError: Job name must be formatted: "projects/<PROJECT_ID>/locations/<LOCATION_ID>/jobs/<JOB_ID>".
    at Gaxios.request (/backend/node_modules/gaxios/src/gaxios.ts:86:15)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at JWT.requestAsync (/backend/node_modules/google-auth-library/build/src/auth/oauth2client.js:346:18) {
  response: {
    config: {
      url: 'https://cloudscheduler.googleapis.com/v1/projects/<Took-0ff>/locations/us-central1/jobs',
      method: 'POST',
      paramsSerializer: [Function],
      data: [Object],
      headers: [Object],
      params: [Object: null prototype] {},
      validateStatus: [Function],
      retry: true,
      body: '{"name":"nameJob","description":"This is description","schedule":"* ' +
        '* * * *","httpTarget":{"uri":"https://sign.ly","httpMethod":"GET"}}',
      responseType: 'json',
      retryConfig: [Object]
    },
    data: { error: [Object] },
    headers: {
      'alt-svc': 'quic=":443"; ma=2592000; v="46,43,39"',
      'cache-control': 'private',
      connection: 'close',
      'content-encoding': 'gzip',
      'content-type': 'application/json; charset=UTF-8',
      date: 'Sat, 13 Jul 2019 05:55:28 GMT',
      server: 'ESF',
      'transfer-encoding': 'chunked',
      vary: 'Origin, X-Origin, Referer',
      'x-content-type-options': 'nosniff',
      'x-frame-options': 'SAMEORIGIN',
      'x-xss-protection': '0'
    },
    status: 400,
    statusText: 'Bad Request'
  },
  config: {
    url: 'https://cloudscheduler.googleapis.com/v1/projects/<Took-0ff>/locations/us-central1/jobs',
    method: 'POST',
    paramsSerializer: [Function],
    data: {
      name: 'nameJob',
      description: 'This is description',
      schedule: '* * * * *',
      httpTarget: [Object]
    },
    headers: {
      'Accept-Encoding': 'gzip',
      'User-Agent': 'google-api-nodejs-client/2.0.4 (gzip)',
      Authorization: 'Bearer ' +
        '<Took-0ff>',
      'Content-Type': 'application/json',
      Accept: 'application/json'
    },
    params: [Object: null prototype] {},
    validateStatus: [Function],
    retry: true,
    body: '{"name":"nameJob","description":"This is description","schedule":"* ' +
      '* * * *","httpTarget":{"uri":"https://sign.ly","httpMethod":"GET"}}',
    responseType: 'json',
    retryConfig: {
      currentRetryAttempt: 0,
      retry: 3,
      retryDelay: 100,
      httpMethodsToRetry: [Array],
      noResponseRetries: 2,
      statusCodesToRetry: [Array]
    }
  },
  code: 400,
  errors: [
    {
      message: 'Job name must be formatted: ' +
        '"projects/<PROJECT_ID>/locations/<LOCATION_ID>/jobs/<JOB_ID>".',
      domain: 'global',
      reason: 'badRequest'
    }
  ]
}
```
And if I give job name at the end then the error is 
```
Exception while creating a job. GaxiosError: <!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 404 (Not Found)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>404.</b> <ins>That’s an error.</ins>
  <p>The requested URL <code>/v1/projects/<Took it off purposefully>/locations/us-central1/jobs/jobName</code> was not found on this server.  <ins>That’s all we know.</ins>

    at Gaxios.request (/backend/node_modules/gaxios/src/gaxios.ts:86:15)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at JWT.requestAsync (/backend/node_modules/google-auth-library/build/src/auth/oauth2client.js:346:18) {
  response: {
    config: {
      url: 'https://cloudscheduler.googleapis.com/v1/projects/<Took it off purposefully>/locations/us-central1/jobs/jobName',
      method: 'POST',
      paramsSerializer: [Function],
      data: [Object],
      headers: [Object],
      params: [Object: null prototype] {},
      validateStatus: [Function],
      retry: true,
      body: '{"name":"nameJob","description":"This is description","schedule":"* ' +
        '* * * *","httpTarget":{"uri":"https://sign.ly","httpMethod":"GET"}}',
      responseType: 'json',
      retryConfig: [Object]
    },
    data: '<!DOCTYPE html>\n<html lang=en>\n  <meta charset=utf-8>\n  <meta ' +
      'name=viewport content="initial-scale=1, minimum-scale=1, ' +
      'width=device-width">\n  <title>Error 404 (Not Found)!!1</title>\n  ' +
      '<style>\n    *{margin:0;padding:0}html,code{font:15px/22px ' +
      'arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% ' +
      'auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > ' +
      'body{background:url(//www.google.com/images/errors/robot.png) 100% 5px ' +
      'no-repeat;padding-right:205px}p{margin:11px 0 ' +
      '22px;overflow:hidden}ins{color:#777;text-decoration:none}a ' +
      'img{border:0}@media screen and ' +
      '(max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) ' +
      'no-repeat;margin-left:-5px}@media only screen and ' +
      '(min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) ' +
      'no-repeat 0% 0%/100% ' +
      '100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) ' +
      '0}}@media only screen and ' +
      '(-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) ' +
      'no-repeat;-webkit-background-size:100% ' +
      '100%}}#logo{display:inline-block;height:54px;width:150px}\n  </style>\n  ' +
      '<a href=//www.google.com/><span id=logo aria-label=Google></span></a>\n  ' +
      '<p><b>404.</b> <ins>That’s an error.</ins>\n  <p>The requested URL ' +
      '<code>/v1/projects/<Took it off purposefully>/locations/us-central1/jobs/jobName</code> ' +
      'was not found on this server.  <ins>That’s all we know.</ins>\n',
    headers: {
      'alt-svc': 'quic=":443"; ma=2592000; v="46,43,39"',
      connection: 'close',
      'content-length': '1620',
      'content-type': 'text/html; charset=UTF-8',
      date: 'Sat, 13 Jul 2019 05:47:30 GMT',
      server: 'ESF',
      'x-content-type-options': 'nosniff',
      'x-frame-options': 'SAMEORIGIN',
      'x-xss-protection': '0'
    },
    status: 404,
    statusText: 'Not Found'
  },
  config: {
    url: 'https://cloudscheduler.googleapis.com/v1/projects/<Took it off purposefully>/locations/us-central1/jobs/jobName',
    method: 'POST',
    paramsSerializer: [Function],
    data: {
      name: 'nameJob',
      description: 'This is description',
      schedule: '* * * * *',
      httpTarget: [Object]
    },
    headers: {
      'Accept-Encoding': 'gzip',
      'User-Agent': 'google-api-nodejs-client/2.0.4 (gzip)',
      Authorization: 'Bearer ' +
        '--------took it off purposefully----',
      'Content-Type': 'application/json',
      Accept: 'application/json'
    },
    params: [Object: null prototype] {},
    validateStatus: [Function],
    retry: true,
    body: '{"name":"nameJob","description":"This is description","schedule":"* ' +
      '* * * *","httpTarget":{"uri":"https://sign.ly","httpMethod":"GET"}}',
    responseType: 'json',
    retryConfig: {
      currentRetryAttempt: 0,
      retry: 3,
      retryDelay: 100,
      httpMethodsToRetry: [Array],
      noResponseRetries: 2,
      statusCodesToRetry: [Array]
    }
  },
  code: '404'
}
```

Thanks!

**Comment by JustinBeckwith** [comment]
Greetings!  It looks like you're trying to use the [googleapis](npm.im/googleapis) npm module to access scheduler.  If that's the case ... this isn't the right repository!  

I would suggest following along with the quickstart over in the [README](https://github.com/googleapis/nodejs-scheduler).  Specifically I would:
- Remove `googleapis` from your `package.json`
- `npm install @google-cloud/scheduler`
- Start with the code snippet over in the readme

After that if you're still having trouble ... let us know!

**Comment by gduggirala** [comment]
There is no types defined for typescript for @google-cloud/scheduler.

So I took this package.
I thought "googleapis/nodejs-scheduler" is an official package as well.

Currently I am using "googleapis": "^41.0.0" package.

Thank you,
Giridhar Duggirala.

**Comment by gduggirala** [comment]
Resolved the error, after revisiting after a long time.

The name of the job should be formatted as follows.

`projects/${ScheduleJobService.client.projectId}/locations/${location}/jobs/${jobName}`
