### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by shamoons** [googleapis/nodejs-scheduler#131]
I'm doing:
```
const scheduler = require('@google-cloud/scheduler')
const schedulerClient = new scheduler.CloudSchedulerClient()
```

But the error I get is:
```
TypeError: Cannot read property 'length' of undefined
    at Root.load (/c/Users/Shamoon/Sites/olive/olive-api/node_modules/protobufjs/src/root.js:192:44)
    at Root.loadSync (/c/Users/Shamoon/Sites/olive/olive-api/node_modules/protobufjs/src/root.js:235:17)
    at Object.loadSync (/c/Users/Shamoon/Sites/olive/olive-api/node_modules/@grpc/proto-loader/build/src/index.js:230:27)
    at GrpcClient.loadFromProto (/c/Users/Shamoon/Sites/olive/olive-api/node_modules/google-gax/build/src/grpc.js:118:44)
    at GrpcClient.loadProto (/c/Users/Shamoon/Sites/olive/olive-api/node_modules/google-gax/build/src/grpc.js:145:21)
    at new CloudSchedulerClient (/c/Users/Shamoon/Sites/olive/olive-api/node_modules/@google-cloud/scheduler/src/v1/cloud_scheduler_client.js:121:28)
    at Object.<anonymous> (/c/Users/Shamoon/Sites/olive/olive-api/controllers/calendar.js:18:16)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.<anonymous> (/c/Users/Shamoon/Sites/olive/olive-api/node_modules/@sentry/node/dist/integrations/console.js:40:47)
    at Function._load (/c/Users/Shamoon/Sites/olive/olive-api/node_modules/@sentry/node/dist/integrations/http.js:63:47)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/c/Users/Shamoon/Sites/olive/olive-api/micro/calendar.js:2:28)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

I'm using:
```
        "@google-cloud/scheduler": "^1.2.0",
```

**Comment by callmehiphop** [comment]
👋 @shamoons thanks for opening an issue! I tried running this on my local machine I was unable to reproduce your issue. Would you mind providing some additional information like your OS and Node.js version?

**Comment by shamoons** [comment]
Using node.js v `v10.16.0`. OS is Ubuntu 16.04

**Comment by callmehiphop** [comment]
:wave: @shamoons Which version of google-gax is downloaded in your node_modules? Can you please run `npm ls` and paste the output?

If google-gax is older than 1.5.2 then please do `rm -rf node_modules package-lock.json`, reinstall and make sure it's recent.

Thank you!

**Comment by henriquejensen** [comment]
I solved it after removing `cache`, `dist` and `node_modules` folder and upgrading my node to 13.6 version.
Probably this is an error with Node 13 version. https://github.com/babel/babel/issues/10997#issuecomment-575050066

**Comment by bcoe** [comment]
@shamoons can you confirm that this approach worked for you?

**Comment by shamoons** [comment]
Yup - that did it.
