### ISSUE TITLE
Error creating schedule with a pubsubTarget

### ISSUE THREAD

**Issue by brianschardt** [googleapis/nodejs-scheduler#291]
This issue is with this client library
Node version: v12.18.0
Npm: 6.14.4
Os: Mac
#### Steps to reproduce

```
const [response] = await client.createJob({
      parent,
      job: {
        pubsubTarget: {
          topicName: `projects/${projectId}/topics/${process.env.JOB_QUEUE_TOPIC}`,
          data: JSON.stringify({ name: "testing1", data: { test: "data" } }),

        },
        name: parent + '/jobs/test',
        schedule: '*/20 * * * *',
        timeZone: 'America/Los_Angeles',
      }
    });
```

After doing that I get this error:

```
Error: 13 INTERNAL: Request message serialization failure: invalid encoding at Object.callErrorFromStatus (/usr/src/app/node_modules/@grpc/grpc-js/build/src/call.js:30:26) at Object.onReceiveStatus 
(/usr/src/app/node_modules/@grpc/grpc-js/build/src/client.js:175:52) at Object.onReceiveStatus 
(/usr/src/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:341:141) at Object.onReceiveStatus 
(/usr/src/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:304:181) at Http2CallStream.outputStatus 
(/usr/src/app/node_modules/@grpc/grpc-js/build/src/call-stream.js:116:74) at Http2CallStream.maybeOutputStatus 
(/usr/src/app/node_modules/@grpc/grpc-js/build/src/call-stream.js:155:22) at Http2CallStream.endCall 
(/usr/src/app/node_modules/@grpc/grpc-js/build/src/call-stream.js:141:18) at Http2CallStream.cancelWithStatus (/usr/src/app/node_modules/@grpc/grpc-js/build/src/call-stream.js:457:14) at 
BaseUnaryInterceptingCall.sendMessageWithContext (/usr/src/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:267:23) at BaseUnaryInterceptingCall.sendMessage (/usr/src/app/node_modules/@grpc/grpc-
js/build/src/client-interceptors.js:272:14)
```

**Comment by brianschardt** [comment]
Solution found 
in this line 
```
data: JSON.stringify({ name: "testing1", data: { test: "data" } }),
```

you need the type to be a buffer
```
data: Buffer.from('Hello World'),
```
